### ISSUE TITLE
Log requests of pages

### ISSUE THREAD

**Issue by Baschdl** [match4healthcare/match4healthcare#112]
Self-hosted alternative for Google Analytics

**Comment by kevihiiin** [comment]
Installed on server, need to check data privacy concerns

**Comment by Baschdl** [comment]
We won't use Matomo, just log if a site is accessed and when but without any further data

**Comment by josauder** [comment]
Can we close this issue? Do the current logs work? @Baschdl

**Comment by Baschdl** [comment]
Logs work, need to build visualization
