### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by bjrne** [match4healthcare/match4healthcare#116]
## Refer to it in:
- [ ] accounts/views.py login_redirect

**Comment by Baschdl** [comment]
Vielleicht so eine Visualisierung: [https://thenounproject.com/search/?q=heartbeat&i=1382202](https://thenounproject.com/search/?q=heartbeat&i=1382202). Nur, dass der heartbeat aufhört

**Comment by maltezacharias** [comment]
Bitte auch für Fehler 500 anlegen.
Reicht sicherlich wenn beides leere Seiten sind im normalen Design und @andyz02 dann Bescheid geben, dass er sie füllt

**Comment by bjrne** [comment]
404 existiert jetzt, das TODO von oben ist aber noch nicht umgesetzt, dafür gibts jetzt ein neues Issue: #289
