### ISSUE TITLE
Merge Medizinstudent und Arzt

### ISSUE THREAD

**Issue by maltezacharias** [match4healthcare/match4healthcare#121]
# Zusammenfassen von Arzt und Medizinstudent als eine Berufsausbildung.
Auf der Onboarding Seite soll folgendermaßen geändert werden:

## **Abschnitt Arzt:** 
entfällt

## Abschnitt Student wird folgendermassen geändert:
**Mediziner_In**

1. Ausbildungsabschnitt (Auswahl)
    1. Keine Angabe
    2. Vorklinischer Teil (1.-5. Semester)
    3. Klinischer Teil (6.-10. Semester)
    4. Praktisches Jahr
    5. Assistenzarzt
    6. Facharzt
2. Erfahrung/Fachrichtung Anästhesie
3. Erfahrung/Fachrichtung Famulatur Chirurgie
4. Erfahrung/Fachrichtung Famulatur Innere
5. Erfahrung/Fachrichtung Famulatur Intensivmedizin
6. Erfahrung/Fachrichtung Notaufnahme
7. Eine Anerkennung als Teil eines Studienabschnitts (Pflegepraktikum/Famulatur) ist wichtig

## Weiteres
**Wenn kein Aufwand**, Zahnmedizinstudent_in noch um Abgeschlossen erweitern als letzte Stufe

# Filterseite
Auswahl des Abschnitts einmal als Minimum, einmal als Maximum:
"Mindestens Keine Angabe|Vorklinischer Teil (1.-5. Semester)|..."
"Höchstens   Keine Angabe|Vorklinischer Teil (1.-5. Semester)|..."

**Comment by feeds** [comment]
#122 added to be able to close this

**Comment by maltezacharias** [comment]
Ist nicht richtig umgesetzt, die Texte im Formular sind nicht so wie hier spezifiziert. Wichtig, weil die Studis sich jetzt nicht auskennen und die main target group sind

**Comment by maltezacharias** [comment]
Außerdem: 
    2. Vorklinischer Teil (1.-4. Semester)
    3. Klinischer Teil (5.-10. Semester)

Da stand bisher 1.-5. und 5.-10. (Ganz oben hab ichs upgedated, hier extra, damit es nicht untergeht)

**Comment by josauder** [comment]
"Ich bin da anderer Meinung: Das Problem ist, dass das an manchen Unis anders gehandlet wird. In Berlin gibts eine Einteilung in diese beiden Teile aufgrund des Modellstudiengangs nicht. Deswegen würde ich vorschlagen, die Semesteranzahl am besten weg zu lassen." Zitat Andi Kind

**Comment by feeds** [comment]
@maltezacharias also was ist jetzt sache?

**Comment by maltezacharias** [comment]
@feeds Das **wichtigtste** ist der Punkt dass bei Anästhesie usw. nicht Famulatur/Fachrichtung dabei steht. Die Semesterzahl weglassen ist ok. So machen wie @andreaskind gesagt hat aber v.a. nicht die anderen Texte vergessen

**Comment by feeds** [comment]
Wir haben klarifiziert was im aktuellen branch ist, das passt so
