### ISSUE TITLE
Possible Bug: Crash on User Registration

### ISSUE THREAD

**Issue by maltezacharias** [match4healthcare/match4healthcare#218]
FB DE Covid Feedback:
![image](https://user-images.githubusercontent.com/9914287/77733566-62081400-7007-11ea-90eb-11c93ae27d74.png)
(von Michael Neulinger)

Please check logs for server crash and/or error and specify issue

**Comment by maltezacharias** [comment]
https://match4healthcare.slack.com/archives/C010K4T5YGZ/p1585292357037100
Warte noch auf e-Mail Adresse zum überprüfen können und genaue Uhrzeit

Lt. @Baschdl haben wir zu der Zeit deployed, also sehr wahrscheinlich kein echter Bug

**Comment by kevihiiin** [comment]
Ich glaube das ist der selbe Fehler wie Issue #204

**Comment by maltezacharias** [comment]
Mischung wahrscheinlich. Der Server Error war dann das deployment und das andere das doppelt abschicken. Ich warte noch auf die Mail Adresse (muss über FB angefragt werden und verify das dann zur Sicherheit.

**Comment by maltezacharias** [comment]
Lt. Basti erledigt
