### ISSUE TITLE
Log-In Form: Add note concerning username and e-mail delivery time

### ISSUE THREAD

**Issue by maltezacharias** [match4healthcare/match4healthcare#220]
Bitte Hinweis am Nutzerformular einfügen:

> Deine e-Mail Adresse ist gleichzeitig dein Benutzername. In Einzelfällen kann es etwas dauern, bis die Bestätigungsmail dich erreicht, da einige e-Mail Anbieter diese nicht sofort durchlassen

Reason:
https://match4healthcare.slack.com/archives/C010K4T5YGZ/p1585245475001000
![image](https://user-images.githubusercontent.com/9914287/77735644-3b4bdc80-700b-11ea-86a7-c35d2caa79b9.png)

(Plus weitere Berichte)

**Comment by andyz02** [comment]
We changed “Benutzername” to “E-Mail” already. We have to check if it is still implemented.

**Comment by Baschdl** [comment]
It is stil implemented

**Comment by Baschdl** [comment]
IMO Would be better placed below "Register" button but closed for now because we don't have problems sending mails
