### ISSUE TITLE
Asynchrones Email Backend einstellen (Kevin)

### ISSUE THREAD

**Issue by feeds** [match4healthcare/match4healthcare#49]

**Comment by kevihiiin** [comment]
Ich habe Celery eingerichtet um asynchron Mails zu verschicken, ist das Feld "was_sent" in dem Model noch notwendig? Sollte eine Institution sich nicht zuerst verifizieren und dann E-Mails senden können (falls ja, wäre ein Hinweis glaube ich gut)?

**Comment by maltezacharias** [comment]
@Baschdl ist das noch aktuell? Ich dachte wir nehmen die sendgrid API oder brauchen wir da noch eine Vermittlung?

**Comment by maltezacharias** [comment]
Bzw. was ist hier noch das konkrete ToDo?

**Comment by kevihiiin** [comment]
Ich dachte der Stand von gestern war noch, dass wir nur eine normale SMTP Verbindung aufbauen. Nutzen wir Sendgrid? Ansonsten wäre das auch noch aktuell, da Mails asynchron submitten doch recht sinnvoll sein kann (je nach Anzahl der Mails). Evlt lässt sich der Issue aber mit #4 mergen

**Comment by josauder** [comment]
> Ich habe Celery eingerichtet um asynchron Mails zu verschicken, ist das Feld "was_sent" in dem Model noch notwendig? Sollte eine Institution sich nicht zuerst verifizieren und dann E-Mails senden können (falls ja, wäre ein Hinweis glaube ich gut)?

Field was_sent ist relevant. Wir zeigen den Institutions an, dass ihre mail geschickt wurde, schicken sie aber erst wenn sie verifiziert ist.
