### ISSUE TITLE
Correct wrong validation message

### ISSUE THREAD

**Issue by bjrne** [match4healthcare/match4healthcare#63]
Validation message is correct in validation function in `iamstudent/models.py:validate_checkboxes`, but another one appears in student registration form:
![Screenshot from 2020-03-25 02-33-09](https://user-images.githubusercontent.com/7229585/77492593-3b987c00-6e41-11ea-8fbe-ebb2b3591ae9.png)

**Comment by josauder** [comment]
Same happens now with Unterkunft

**Comment by josauder** [comment]
Still an issue (Friday night)
